apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.ui.name }}
  labels:
    app: {{ .Values.services.ui.name }}
    cluster: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.services.ui.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.ui.name }}
        cluster: frontend
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: {{ .Values.services.ui.name }}
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        image: {{ .Values.global.image.repository }}/{{ .Values.services.ui.image }}:{{ .Values.global.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.services.ui.port }}
        env:
        - name: VITE_EXCHANGE_APP_API_URL
          value: {{ .Values.services.ui.config.exchangeAppApiUrl }}
        - name: VITE_LOGISTICS_APP_API_URL
          value: {{ .Values.services.ui.config.logisticsAppApiUrl }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.ui.name }}
  labels:
    app: {{ .Values.services.ui.name }}
    cluster: frontend
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: {{ .Values.services.ui.port }}
    name: http
  selector:
    app: {{ .Values.services.ui.name }}
