apiVersion: v2
name: lungo-frontend
description: Lungo Frontend Cluster - UI and Logistics Supervisor
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  # External secrets for production secret management
  - name: external-secrets
    version: "0.9.3"
    repository: "https://charts.external-secrets.io"
  # Monitoring only
  - name: grafana
    version: "8.5.2"
    repository: "https://grafana.github.io/helm-charts"
