apiVersion: v2
name: lungo-dual-llm
description: A Helm chart for deploying Lungo on a single cluster with separate LLM configurations for frontend and backend services
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  # External infrastructure - mix of OCI and HTTP based on availability
  - name: external-secrets
    version: "0.9.3"
    repository: "https://charts.external-secrets.io"
  - name: slim
    version: "v0.6.0"
    repository: "oci://ghcr.io/agntcy/slim/helm"
  - name: nats
    version: "1.3.16"
    repository: "https://nats-io.github.io/k8s/helm/charts"
  - name: clickhouse
    version: "9.4.3"
    repository: "oci://registry-1.docker.io/bitnamicharts"
  - name: opentelemetry-collector
    version: "0.138.0"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
  - name: grafana
    version: "10.1.2"
    repository: "oci://ghcr.io/grafana/helm-charts"
