# UI Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.ui.name }}
  labels:
    app: {{ .Values.services.ui.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.services.ui.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.ui.name }}
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: {{ .Values.services.ui.name }}
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
        image: {{ .Values.global.image.repository }}/{{ .Values.services.ui.image }}:{{ .Values.global.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.services.ui.port }}
        env:
        - name: VITE_EXCHANGE_APP_API_URL
          value: {{ .Values.services.ui.config.exchangeAppApiUrl }}
        - name: VITE_LOGISTICS_APP_API_URL
          value: {{ .Values.services.ui.config.logisticsAppApiUrl }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.ui.name }}
  labels:
    app: {{ .Values.services.ui.name }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: {{ .Values.services.ui.port }}
    name: http
  selector:
    app: {{ .Values.services.ui.name }}
---
# Weather MCP Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.weatherMcp.name }}
  labels:
    app: {{ .Values.services.weatherMcp.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.services.weatherMcp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.weatherMcp.name }}
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: {{ .Values.services.weatherMcp.name }}
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
        image: {{ .Values.global.image.repository }}/{{ .Values.services.weatherMcp.image }}:{{ .Values.global.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.services.weatherMcp.port }}
        env:
        - name: TRANSPORT_SERVER_ENDPOINT
          value: {{ .Values.transport.nats.endpoint }}
        - name: DEFAULT_MESSAGE_TRANSPORT
          value: {{ .Values.transport.nats.type }}
        - name: OTLP_HTTP_ENDPOINT
          value: {{ .Values.observability.otlpEndpoint }}
        - name: LLM_MODEL
          value: {{ .Values.llm.model }}
        {{ if .Values.externalSecrets }}
        # NVIDIA NIM
        - name: NVIDIA_NIM_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: llm-api-key
        - name: NVIDIA_NIM_API_BASE
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: nvidia-api-base
        {{ else }}
        # NVIDIA NIM
        - name: NVIDIA_NIM_API_KEY
          value: {{ .Values.llm.apiKey }}
        - name: NVIDIA_NIM_API_BASE
          value: {{ .Values.llm.apiBase }}
        {{ end }}
        - name: LLM_TEMPERATURE
          value: {{ .Values.llm.temperature | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.weatherMcp.name }}
  labels:
    app: {{ .Values.services.weatherMcp.name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.services.weatherMcp.port }}
    name: http
  selector:
    app: {{ .Values.services.weatherMcp.name }}
